{% set name = "premise" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a305369f28d1db920ff25b133fe82289c6a906ec64fd8c5f446d601e2b3b186d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<3.11
    - setuptools
  run:
    - bw2data
    - bw2io =0.8.7
    - cryptography
    - datapackage
    - numpy
    - pandas
    - premise_gwp
    - prettytable
    - pycountry
    - python >=3.9,<3.11
    - pyyaml
    - schema
    - sparse
    - wurst =0.3.3
    - xarray

test:
  imports:
    - premise

about:
  home: https://premise.readthedocs.io
  summary: Coupling IAM output to ecoinvent LCA database ecoinvent for prospective LCA
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://premise.readthedocs.io
  dev_url: https://github.com/polca/premise

extra:
  recipe-maintainers:
    - m-rossi
