{% set name = "premise" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d167ca88a9bcefbc9cbb15a0123485c3b7fd2756f57e0e527aa3668fbfcd082

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10,<3.12
    - setuptools >=61.0
  run:
    - bottleneck
    - bw2data
    - bw2io >=0.8.12
    - constructive_geometries >=0.9.5
    - cryptography
    - datapackage
    - numpy <2.0.0
    - pandas
    - platformdirs
    - premise_gwp
    - prettytable
    - pyarrow
    - pycountry
    - python >=3.10,<3.12
    - pyyaml
    - requests
    - schema
    - sparse >=0.14.0
    - tqdm
    - unfold
    - wurst >=0.4
    - xarray <=2024.2.0

test:
  imports:
    - premise

about:
  home: https://premise.readthedocs.io
  summary: Coupling IAM output to ecoinvent LCA database ecoinvent for prospective LCA
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://premise.readthedocs.io
  dev_url: https://github.com/polca/premise

extra:
  recipe-maintainers:
    - m-rossi
