{% set name = "premise" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb6af0a858e50b4602a62f69be36373aae3e3341aad1dba45ddf83ef72ff186c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - setuptools >=61.0
  run:
    - bottleneck
    - bw2data
    - bw2io >=0.8.10
    - constructive_geometries >=0.8.2
    - cryptography
    - datapackage
    - numpy
    - pandas
    - platformdirs
    - premise_gwp
    - prettytable
    - pyarrow
    - pycountry
    - python >=3.9,<3.12
    - pyyaml
    - schema
    - sparse >=0.14.0
    - wurst
    - xarray

test:
  imports:
    - premise

about:
  home: https://premise.readthedocs.io
  summary: Coupling IAM output to ecoinvent LCA database ecoinvent for prospective LCA
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://premise.readthedocs.io
  dev_url: https://github.com/polca/premise

extra:
  recipe-maintainers:
    - m-rossi
