{% set name = "premise" %}
{% set version = "1.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 277736225ffcbf1e1d1630f98c76fc15bbfc0266d5db4a3f2cf7681e6a38a6c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<3.11
    - setuptools
  run:
    - bottleneck
    - bw2data
    - bw2io =0.8.7
    - constructive_geometries >=0.8.2
    - cryptography
    - datapackage
    - numpy
    - pandas =1.5.3
    - premise_gwp
    - prettytable
    - pycountry
    - python >=3.9,<3.11
    - pyyaml
    - schema
    # Somehow a really old sparse version is installed by default, this seems to solve this solver issue
    - sparse !=0.3.1
    - wurst =0.3.3
    - xarray

test:
  imports:
    - premise

about:
  home: https://premise.readthedocs.io
  summary: Coupling IAM output to ecoinvent LCA database ecoinvent for prospective LCA
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://premise.readthedocs.io
  dev_url: https://github.com/polca/premise

extra:
  recipe-maintainers:
    - m-rossi
